# Generated by Django 5.2.12 on 2026-04-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="phone_number",
            new_name="phone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, help_text="загрузите аватарку", null=True, upload_to="users/avatar", verbose_name="аватар"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "Пользователь"), ("admin", "Администратор")],
                default="user",
                help_text="выберете роль",
                max_length=20,
                verbose_name="роль",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="введите вашу электронную почту", max_length=254, unique=True, verbose_name="почта"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, help_text="введите ваше имя", max_length=30, null=True, verbose_name="имя пользователя"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="введите вашу фамилию",
                max_length=30,
                null=True,
                verbose_name="фамилия пользователя",
            ),
        ),
    ]
