# Generated by Django 5.2.12 on 2026-04-16 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "text",
                    models.TextField(help_text="Ваш отзыв об объявлении или продавце", verbose_name="текст отзыва"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="время и дата создания")),
                (
                    "ad",
                    models.ForeignKey(
                        help_text="Объявление, под которым оставлен отзыв",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="ads.ad",
                        verbose_name="объявление",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Пользователь, оставивший отзыв",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор отзыва",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-created_at"],
                "unique_together": {("author", "ad")},
            },
        ),
    ]
