# Generated by Django 5.2.12 on 2026-04-14 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название категории",
                        max_length=100,
                        unique=True,
                        verbose_name="Название категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Ad",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Укажите заголовок (не более 200 символов)", max_length=200, verbose_name="Заголовок"
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="подробное описание товара или услуги", verbose_name="описание"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="цена в рублях (не может быть отрицательной)",
                        max_digits=10,
                        verbose_name="цена",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="ads/image", verbose_name="изображение")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="обновлено")),
                ("is_active", models.BooleanField(default=True, verbose_name="активно")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads",
                        to="ads.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
                "ordering": ["-created_at"],
            },
        ),
    ]
